### ISSUE TITLE
Not working since 11.0

### ISSUE THREAD

**Issue by allogator** [carbohydrate/Whistle#1]
Casn't click LDB or minimap button to summon pet and even though it displays a chose pet in the LDB the macro won't summon a pet.

4x Whistle/Whistle.lua:172: attempt to call global 'EasyMenu' (a nil value)
[string "@Whistle/Whistle.lua"]:172: in function <Whistle/Whistle.lua:170>
[string "@Titan/TitanLDB.lua"]:302: in function <Titan/TitanLDB.lua:300>

Locals:
self = TitanPanelWhistleButton {
 TitanAction = "None"
 titan_tt_func = ""
 plugin_id = "Whistle"
 titan_tt_err = ""
 TitanName = "Whistle"
 plugin_frame = "TitanPanelWhistleButton"
 registry = <table> {
 }
 TitanCreatedBy = "LDB"
}
button = "LeftButton"
(*temporary) = nil
(*temporary) = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
}
(*temporary) = WhistleMenu {
 Text = WhistleMenuText {
 }
 Icon = WhistleMenuIcon {
 }
 Button = WhistleMenuButton {
 }
 Right = WhistleMenuRight {
 }
 Middle = WhistleMenuMiddle {
 }
 Left = WhistleMenuLeft {
 }
}
(*temporary) = TitanPanelWhistleButton {
 TitanAction = "None"
 titan_tt_func = ""
 plugin_id = "Whistle"
 titan_tt_err = ""
 TitanName = "Whistle"
 plugin_frame = "TitanPanelWhistleButton"
 registry = <table> {
 }
 TitanCreatedBy = "LDB"
}
(*temporary) = 20
(*temporary) = 4
(*temporary) = "MENU"
(*temporary) = "attempt to call global 'EasyMenu' (a nil value)"
menu = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
}
popupFrame = WhistleMenu {
 Text = WhistleMenuText {
 }
 Icon = WhistleMenuIcon {
 }
 Button = WhistleMenuButton {
 }
 Right = WhistleMenuRight {
 }
 Middle = WhistleMenuMiddle {
 }
 Left = WhistleMenuLeft {
 }
}

**Comment by carbohydrate** [comment]
Sorry just saw this, I assumed that GitHub would e-mail me when a new issue was opened.  I need to figure that out.

Will take a look at it in the next few days.

**Comment by carbohydrate** [comment]
I started to look at it tonight, I pushed a new update, but still more work to do.
It should at least load / not crash anymore.
Things I need to work on
- [X] GetStablePetInfo was deprecated.
- [X] SetPetSlot was deprecated.
- [X] EasyMenu removed. Found copy paste replacement.
- [x] Marco normal click does not work. Modifiers do (alt/ctrl/shift)
- [x] Icon on mini map for current pet is not shown (I have fixed, but not released yet)

Only way to get it to call your pet right now is by using Whistle keybind. ESC -> options -> keybinds -> other -> Whistle Key -> set.

Let me know if I missed anything or have any different issues.  I'm a bit busy through the weekend, but should deff have time next week to get the rest of the issues resolved.

**Comment by allogator** [comment]
No worries, take your time. I know how hard figuring out this mess can be and you're basically just doing me a favor. I consider myself a fairly smart dude but I looked up a deprecated lua list and tried making the changes and my brain promptly shut down on my first defeat. I've temporarily shifted to my other macro that just has a bunch of modifiers in it so I'm not dead in the water--Whistle has just always been more convenient. ;)

**Comment by carbohydrate** [comment]
I think I have everything working again.  Just pushed new version out.  Let me know if you notice anything not working as it should.

**Comment by allogator** [comment]
Works like a charm! Thanks again

**Comment by allogator** [comment]
Or maybe not. I noticed that my pets kept going "passive" even though they're set to Assist. After  some trial and error I realized it was any time I used my Mend Pet/Whistle macro or my Kill Command/Whistle macro. If I take Whistle out of the equation it works fine.

**Comment by carbohydrate** [comment]
I was able to recreate and track it down.  It seams like this is a change in behavior in WoW, as in:
Take out your pet ->  get in combat -> use the default fly out call pet menu and click the call pet for the pet you have out and it will do the same thing.
I'm not 100% sure the best way around this, but will try and think of something

**Comment by allogator** [comment]
Well that's just insanity. I didn't even think to test just Call Pet on its own. I assumed it was just a bug in whatever LUA changes Blizz made. I'll do some fiddling of my own and open a Bug Report in the Blizz forums. [nopet] is already a part of the /click isn't it? You'd think that would be all it would need to work properly.

**Comment by allogator** [comment]
Yup, that did it. I saw in your .lua notes that /click could no longer run with macros however you can add [nopet] TO the macro. I'll still make a bug report because that's the weirdest issue ever but here's my new macro:

#showtooltip
/cast [@pet,dead] Revive Pet
/cast [btn:2, @pet,exists] Dismiss Pet; [btn:2,nopet] Revive Pet
/click [nopet]WhistleFrame LeftButton 1
/cast [@pet,exists,nodead] Mend Pet


I just had to manually add in my own [nopet] since it used to be built into Whistle directly.

**Comment by carbohydrate** [comment]
Oh nice find!  I wonder if that just has always been the behavior of call pet, could have been, but hard telling.

I had a hard time trying to figure out that SetAttribute change.  What is allowed and what is not is basically not documented anywhere and just trial and error along with asking in the UI discord.  There might be a way to get that behavior back in the addon, but I have no idea how to do it and have not found good documentation on what is allowed with that SetArrtibute stuff.

I think I'll just leave it be and update the README with the [nopet] change in the /click macro.

**Comment by allogator** [comment]
Yeah, definitely no worries. I almost wouldn't doubt it has always been this way and I just never knew since [nopet] was built in. I'll Bug Forum it for fun but grand scheme of things we're good!
